name: Continuous Training Pipeline (CT)

on:
  repository_dispatch:
    types: [trigger_retraining]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  retrain-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Real Model Retraining
      run: |
        echo "Iniciando reentrenamiento real en la máquina local..."
        docker exec api python src/training/train.py

    - name: Reload API Model
      run: |
        echo "Avisando a la API para que cargue el nuevo modelo en memoria..."
        curl -X POST http://localhost:8000/model/reload

    # --- LA SOLUCIÓN: Configuramos Buildx para el self-hosted runner ---
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert owner to lowercase
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push updated API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.api
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER }}/data-drift-api:latest

    - name: Notify Success
      run: |
        echo "¡Reentrenamiento MLOps completado de principio a fin!"